/************************************************
Treehouse Techdegree:
Project 4 - Random Quote Generator
*************************************************/

// For assistance:
  // Check the "Project Resources" section of the project instructions
  // Reach out in your Slack community

/***
 * Constants with urls where I found the quotes
 */

const goodreads = `<a href="https://www.goodreads.com/quotes" target="_blank">(goodreads.com)</a>`;
const stacker = `<a href="https://stacker.com/stories/2617/can-you-name-who-said-these-50-famous-quotes" target="_blank">(stacker.com)</a>`;
const phactual = `<a href="https://www.phactual.com/17-popular-quotes-youve-always-heard-but-who-said-them/" target="_blank">(phactual.com)</a>`;

/***
 * `quotes` array containing different "quote"-objects  
***/

const quotes = [
  {
    quote: "Live is what happens when you're busy making other plans.",
    source: "Allen Saunders",
    citation: "Reader's Digest",
    year: "1957",
    resource: stacker
  },
  {
    quote: "The best and most beautiful things in the world cannot be seen nor even touched, but just felt in the heart.",
    source: "Hellen Keller / Anne Sullivan",
    citation: "The Story of My Life",
    year: "1905",
    resource: stacker
  },
  {
    quote: "When the whole world is silent, even one voice becomes powerful.",
    source: "Malala Yousafzai",
    citation: "Quote from a speech to an United Nations panel, New York",
    year: "July 12, 2013",
    resource: stacker
  },
  {
    quote: "To err is human; to forgive, divine.",
    source: "Alexander Pope",
    citation: "An Essay on Criticism",
    resource: stacker
  },
  {
    quote: "You've gotta dance like there's nobody watching, love like you'll never be hurt, sing like there's nobody listening, and live like it's heaven on earth.",
    source: "William W. Purkey",
    resource: goodreads
  },
  {
    quote: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    source: "Maya Angelou",
    resource: goodreads
  },
  {
    quote: "Choose a job you love, and you will never have to work a day in your life.",
    source: "Confucius",
    resource: phactual
  },
  {
    quote: "Nothing is impossible, the word itself says ‘I’m possible’!",
    source: "Audrey Hepburn",
    resource: phactual
  },
  {
    quote: "All you need is love. But a little chocolate now and then doesn't hurt.",
    source: "Charles M. Schulz",
    resource: goodreads
  },
  {
    quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    source: "Albert Einstein",
    resource: goodreads
  }  
];

/**
 * `randomColor` function
 * generates a random, not too bright color
 ***/
randomNumber = () => Math.floor(Math.random() * 256) - 50;
randomColor = () => `rgb(${randomNumber()}, ${randomNumber()}, ${randomNumber()})`;

/***
 * `getRandomQuote` function 
 * choses a random quote from an array
***/
function getRandomQuote(arr) {
  const index = Math.floor(Math.random() * arr.length);
  return arr[index];
}


/***
 * `printQuote` function
 * returns an html element with the randomly chosen quote,
 * stored inside `randomQuote`, generated by `getRandomQuote()` function
 * with the `quote` array passed in as the argument
 * additionally, it changes the background-color randomely
***/
function printQuote() {

  let html = "";
  const randomQuote = getRandomQuote(quotes);

  html += `<p class="quote">${randomQuote.quote}</p>
  <p class="source">${randomQuote.source}`;

  if (randomQuote.citation) {
    html+= `<span class="citation">${randomQuote.citation}</span>`;
  }
  if (randomQuote.year) {
    html+= `<span class="year">${randomQuote.year}</span>`;
  }
  if (randomQuote.resource) {
    html+= ` <span class="resource">${randomQuote.resource}</span>`;
  }
  html+= `</p>`;

  document.getElementById('quote-box').innerHTML = html; 
  document.querySelector("body").style.backgroundColor = randomColor();
}

setInterval(printQuote, 6000);

/***
 * click event listener for the print quote button
 * DO NOT CHANGE THE CODE BELOW!!
***/

document.getElementById('load-quote').addEventListener("click", printQuote, false);